config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :users
  devise_scope :user do
      root :to => 'home#top'
  end
  get 'home/about' => 'home#about'
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :rooms

  get 'search/search'

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
def create
	@book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
    	# redirect_back(fallback_location: book_path(book))
    end
end

def destroy
	@book = Book.find(params[:book_id])
	@book_comment = @book.book_comments.find(params[:id])
	if @book_comment.destroy
		# redirect_back(fallback_location: book_path(book))
	end
end

private
def book_comment_params
    params.require(:book_comment).permit(:user_id,:book_id,:comment)
end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
	<%= link_to user_path(book_comment.user), class: "username" do %>
		<%= book_comment.user.name %>
	<% end %>
	<%= book_comment.created_at.strftime('%Y/%m/%d') %>
	<%= book_comment.comment %>
			<!-- コメント削除ボタン -->
	<%= link_to "DELETE", book_book_comments_path(book_id: book, id: book_comment.id), method: :delete, remote: true %><br>
			<!-- コメント削除ボタン -->
  <% end %>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'comments', book: @book ) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'comments', book: @book ) %>")
$("textarea").val('')