config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :users
  devise_scope :user do
      root :to => 'home#top'
  end
  get 'home/about' => 'home#about'
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :rooms

  get 'search/search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  accepts_nested_attributes_for :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # :foreign_key - 参照先のテーブルの外部キーのカラム名を指定できる
  # -------------自分がフォローしているユーザーとの関連-------------------
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # -----------------------------------------------------------------

  # ------------自分がフォローされるユーザーとの関連----------------------
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # ------------------------------------------------------------------

  # -----------チャット-----------------
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  # ------------------------------------

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end


  attachment :profile_image, destroy: false

  def self.search(divide_method,word)
    if divide_method == "1"
      users = User.where("name LIKE?", "#{word}")
    elsif divide_method == "2"
      users = User.where("name LIKE?", "#{word}%")
    elsif divide_method == "3"
      users = User.where("name LIKE?", "%#{word}")
    elsif divide_method == "4"
      users = User.where("name LIKE?", "%#{word}%")
    else
      users = User.all
    end
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
    @book = Book.find(params[:id]) #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    # 以下チャット機能のため追加
    @currentUserUserRoom = UserRoom.where(user_id: current_user.id)
    @userUserRoom = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserUserRoom.each do |cu|
        @userUserRoom.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      unless @isRoom
        @room = Room.new
        @UserRoom = UserRoom.new
      end
    end
  end

  def index
    @user = current_user
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）

  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>follows</th>
			<th>
				<%= link_to follows_user_path(user.id) do %>
					<%= user.followings.count %>
				<% end %>
			</th>
		</tr>
		<tr>
			<th>followers</th>
			<th><%= link_to followers_user_path(user.id) do %>
					<%= user.followers.count %>
				<% end %>
			</th>
		</tr>
</table>

<div class="row">
	<% if @user == current_user %>
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% else %>
		<%= link_to '', user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench user" %>
	<% end %>
</div>
<div class="row">
	<% if @user != current_user %>
		<% if user.followed_by?(current_user) %>
			<p><%= link_to "フォロー外す", user_relationships_path(@book.user.id), method: :delete %></p>
		<% else %>
			<p><%= link_to "フォローする", user_relationships_path(@book.user.id), method: :post %></p>
		<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        	<% @user.errors.full_messages.each do |msg| %>
        		<li><%= msg %></li>
        	<% end %>
        </ul>
     </div>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<div class="row">
	<table class="table table-hover table-invers">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>フォローボタン</th>
				<th>show</th>
			</tr>
		</thead>

		<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= user.followings.count %></td>
			<td><%= user.followers.count %></td>
			<td>
				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<p><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
					<% else %>
						<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
					<% end %>
				<% end %>
			</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/users/follows.html.erb
<h1>Follow Users</h1>
<div class="row">
	<table class="table table-hover table-invers">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th>フォロー数</th>
				<th>フォロワー数</th>
				<th>フォローボタン</th>
				<th>show</th>
			</tr>
		</thead>

		<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>
			<td><%= user.followings.count %></td>
			<td><%= user.followers.count %></td>
			<td>
				<% if current_user != user %>
					<% if user.followed_by?(current_user) %>
						<p><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
					<% else %>
						<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
					<% end %>
				<% end %>
			</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
	<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

	<h2>New book</h2>
		<%= render 'books/newform', book: Book.new %>
	</div>

	<div class="col-xs-9">


	<h2>Users</h2>
<!--users一覧 -->
	<table class="table table-hover table-invers">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
				<th colspan="3"></th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name%></td>
				<td>フォロー数<%= user.followings.count %> </td>
				<td>フォロワー数<%= user.followers.count %></td>
				<td>
					<% if current_user != user %>
						<% if user.followed_by?(current_user) %>
							<p><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
						<% else %>
							<p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
						<% end %>
					<% end %>
				</td>
				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
	</div>
<!--users一覧 -->
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->
		<div class="row">
			<% unless @user.id == current_user.id %>
  				<% if @isRoom == true %>
    				<%= link_to "チャットへGo!", room_path(@roomId) %>
  				<% else %>
    				<%= form_for @room do |f| %>
      					<%= fields_for @UserRoom do |e| %>
        					<%= e.hidden_field :user_id, :value=> @user.id %>
      					<% end %>
      					<%= f.submit "チャットを始める" %>
    				<% end %>
  				<% end %>
			<% end %>
		</div>

		<h2>New book</h2>
			<%= render 'books/newform', book: Book.new %>
	</div>

	<div class="col-xs-9">

	<h2>Books</h2>
<!--books一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (@book.user) do %>
				<%= attachment_image_tag(@book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
		</tbody>
	</table>
	</div>
</div>
<!--books一覧 -->