config/routes.rb
Rails.application.routes.draw do

  get 'rooms/show'
  devise_for :users
  devise_scope :user do
      root :to => 'home#top'
  end
  get 'home/about' => 'home#about'
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books do
  	resource :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :rooms

  get 'search/search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(divide_method,word)
		if divide_method == "1"
			books = Book.where("title LIKE?", "#{word}")
		elsif divide_method == "2"
			books = Book.where("title LIKE?", "#{word}%")
		elsif divide_method == "3"
			books = Book.where("title LIKE?", "%#{word}")
		elsif divide_method == "4"
			books = Book.where("title LIKE?", "%#{word}%")
		else
			books = Book.all
		end
	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { ChatBroadcastJob.perform_later self }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	# :class_name - 関連するモデルクラス名を指定。関連名と参照先のクラス名を分けたい場合に使う。
	# belongs_to 変更したい親モデル名, class_name: "元々の親モデル名"
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
	has_many :user_rooms
	has_many :chats
	has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books
  accepts_nested_attributes_for :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # :foreign_key - 参照先のテーブルの外部キーのカラム名を指定できる
  # -------------自分がフォローしているユーザーとの関連-------------------
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # -----------------------------------------------------------------

  # ------------自分がフォローされるユーザーとの関連----------------------
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # ------------------------------------------------------------------

  # -----------チャット-----------------
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
  # ------------------------------------

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end


  attachment :profile_image, destroy: false

  def self.search(divide_method,word)
    if divide_method == "1"
      users = User.where("name LIKE?", "#{word}")
    elsif divide_method == "2"
      users = User.where("name LIKE?", "#{word}%")
    elsif divide_method == "3"
      users = User.where("name LIKE?", "%#{word}")
    elsif divide_method == "4"
      users = User.where("name LIKE?", "%#{word}%")
    else
      users = User.all
    end
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book_new = Book.new
  	@book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @books = Book.all
      @user = current_user
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
    @user = @book.user
    if @book.user != current_user
      redirect_to books_path
    end

  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def delete
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end



  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def show
  	@room = Room.find(params[:id])
    #present?の戻り値は真偽値。よって、trueの場合、
    if UserRoom.where(:user_id => current_user.id, :room_id => @room.id).present?
      @chats = @room.chats
      @user_rooms = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.create(:name => "Chat Room")
    @user_room1 = UserRoom.create(:room_id => @room.id, :user_id => current_user.id)
    @user_room2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to room_path(@room.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
    @book = Book.find(params[:id]) #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    # 以下チャット機能のため追加
    @currentUserUserRoom = UserRoom.where(user_id: current_user.id)
    @userUserRoom = UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserUserRoom.each do |cu|
        @userUserRoom.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      unless @isRoom
        @room = Room.new
        @UserRoom = UserRoom.new
      end
    end
  end

  def index
    @user = current_user
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）

  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' Sign Up', user_path(current_user), class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' Sign Up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>
    <!--ヘッダーの記述-->
    
    <!-- 検索 -->
    <% if user_signed_in? %>
    <div class="row" style="text-align: center;">
      <%= form_tag search_search_path, :method => 'get' do %>
        <%= text_field_tag :search_word%>
        <%= select_tag :search_divide_model, options_for_select([['Book','1'], ['User','2']]) %>
        <%= select_tag :search_method, options_for_select([['完全一致','1'], ['前方一致','2'],['後方一致','3'],['部分一致','4']]) %>
        <%= submit_tag "検索" %>
      <% end %>
    </div>
    <% end %>
    <!-- 検索 -->

    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
      <%= yield %>
    </div>
  </body>
</html>